language: node_js

node_js:
  - 12.4.0

cache: yarn

install: 
  - yarn global add jest@24.7.1 react-scripts@3.0.1 --silent

matrix:
  include:
    - name: API Pipeline
      env: PACKAGE_LOCATION=api
    - name: UI Pipeline
      env: PACKAGE_LOCATION=ui

script: 
  - cd $PACKAGE_LOCATION
  - yarn install
  - yarn test
  - yarn build
