version: '3.7'
services:
  api:
    build: ./api
    command: nodemon --watch views -e js,html src/app.js
    depends_on:
      - db
    ports:
      - "3002:3002"
      - "8000:8000"
    volumes:
      - ./api:/api
      - /api/node_modules
  db:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  ui:
    build:
      context: ./ui
      dockerfile: dockerfile.dev
    depends_on:
      - api
    ports:
      - "3001:3001"
    volumes:
      - ./ui:/ui
      - /ui/node_modules


