#App version
version: '3'
#Services
services:
  #API Service
  api:
    build:
      context: ./api
      dockerfile: dockerfile.dev
    ports:
      - "3002:3002"
    volumes:
      - ./api:/api
      - /api/node_modules
  #Database Service
  db:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
  #UI Service
  ui:
    build:
      context: ./ui
      dockerfile: dockerfile.dev
    ports:
      - "3001:3001"
    volumes:
      - ./ui:/ui
      - /ui/node_modules


